const wildlifetrusts = {
    version: 8,
    name: '00535_v5_cgi',
    metadata: {
        'mapbox:origin': 'basic-template-v1',
        'mapbox:autocomposite': true,
        'mapbox:type': 'template',
        'mapbox:sdk-support': { js: '0.45.0', android: '6.0.0', ios: '4.0.0' },
        'mapbox:trackposition': false,
        'mapbox:groups': {
            '49e1fe31d1c813174a5ab59acec3ade6': {
                name: 'Basemap',
                collapsed: true,
            },
        },
    },
    center: [0, -1.1368683772161603e-13],
    zoom: 1.2877122661822635,
    bearing: 0,
    pitch: 0,
    sources: {
        composite: {
            url: 'mapbox://mapbox.mapbox-streets-v7,wildlifetrusts.7a5jh9w3,wildlifetrusts.2rizswe3,wildlifetrusts.1o7iynwb,wildlifetrusts.alk0c2sh',
            type: 'vector',
        },
    },
    sprite: 'mapbox://sprites/wildlifetrusts/cjivgu4ye6het2rnvz5lt591p',
    glyphs: 'mapbox://fonts/wildlifetrusts/{fontstack}/{range}.pbf',
    layers: [
        {
            id: 'background',
            type: 'background',
            layout: {},
            paint: {
                'background-color': [
                    'interpolate',
                    ['linear'],
                    ['zoom'],
                    5,
                    'hsl(147, 43%, 89%)',
                    7,
                    'hsl(123, 47%, 78%)',
                ],
            },
            metadata: { 'mapbox:group': '49e1fe31d1c813174a5ab59acec3ade6' },
        },
        {
            layout: {},
            metadata: { 'mapbox:group': '49e1fe31d1c813174a5ab59acec3ade6' },
            filter: ['==', 'class', 'national_park'],
            type: 'fill',
            source: 'composite',
            id: 'national_park',
            paint: {
                'fill-color': 'hsl(78, 51%, 73%)',
                'fill-opacity': [
                    'interpolate',
                    ['linear'],
                    ['zoom'],
                    5,
                    0,
                    6,
                    0.5,
                ],
            },
            'source-layer': 'landuse_overlay',
        },
        {
            layout: {},
            metadata: { 'mapbox:group': '49e1fe31d1c813174a5ab59acec3ade6' },
            filter: ['in', 'class', 'hospital', 'park', 'pitch', 'school'],
            type: 'fill',
            source: 'composite',
            id: 'landuse',
            paint: {
                'fill-color': [
                    'match',
                    ['get', 'class'],
                    'park',
                    'hsl(78, 51%, 73%)',
                    'pitch',
                    'hsl(78, 51%, 73%)',
                    'hospital',
                    'hsl(0, 56%, 89%)',
                    'school',
                    'hsl(25, 45%, 85%)',
                    'hsla(0, 0%, 0%, 0)',
                ],
                'fill-opacity': [
                    'interpolate',
                    ['linear'],
                    ['zoom'],
                    5,
                    0,
                    6,
                    1,
                ],
            },
            'source-layer': 'landuse',
        },
        {
            minzoom: 8,
            layout: { 'line-join': 'round', 'line-cap': 'round' },
            metadata: { 'mapbox:group': '49e1fe31d1c813174a5ab59acec3ade6' },
            filter: [
                'all',
                ['==', '$type', 'LineString'],
                ['in', 'class', 'canal', 'river'],
            ],
            type: 'line',
            source: 'composite',
            id: 'waterway',
            paint: {
                'line-color': 'hsl(205, 76%, 70%)',
                'line-width': [
                    'interpolate',
                    ['exponential', 1.3],
                    ['zoom'],
                    8.5,
                    0.1,
                    20,
                    8,
                ],
                'line-opacity': [
                    'interpolate',
                    ['linear'],
                    ['zoom'],
                    8,
                    0,
                    8.5,
                    1,
                ],
            },
            'source-layer': 'waterway',
        },
        {
            id: 'water',
            type: 'fill',
            source: 'composite',
            'source-layer': 'water',
            layout: {},
            paint: { 'fill-color': '#75cff1' },
            metadata: { 'mapbox:group': '49e1fe31d1c813174a5ab59acec3ade6' },
        },
        {
            layout: {},
            metadata: { 'mapbox:group': '49e1fe31d1c813174a5ab59acec3ade6' },
            filter: [
                'all',
                ['==', '$type', 'Polygon'],
                ['in', 'type', 'helipad', 'runway', 'taxiway'],
            ],
            type: 'fill',
            source: 'composite',
            id: 'aeroway-polygon',
            paint: { 'fill-color': 'hsl(0, 0%, 77%)' },
            'source-layer': 'aeroway',
        },
        {
            layout: {},
            metadata: { 'mapbox:group': '49e1fe31d1c813174a5ab59acec3ade6' },
            filter: [
                'all',
                ['==', '$type', 'LineString'],
                ['in', 'type', 'runway', 'taxiway'],
            ],
            type: 'line',
            source: 'composite',
            id: 'aeroway-line',
            paint: {
                'line-width': [
                    'interpolate',
                    ['exponential', 1.5],
                    ['zoom'],
                    10,
                    0.5,
                    18,
                    20,
                ],
                'line-color': 'hsl(0, 0%, 77%)',
            },
            'source-layer': 'aeroway',
        },
        {
            minzoom: 15,
            layout: {},
            metadata: { 'mapbox:group': '49e1fe31d1c813174a5ab59acec3ade6' },
            filter: [
                'all',
                ['!=', 'type', 'building:part'],
                ['==', 'underground', 'false'],
            ],
            type: 'fill',
            source: 'composite',
            id: 'building',
            paint: {
                'fill-color': 'hsl(38, 28%, 77%)',
                'fill-opacity': [
                    'interpolate',
                    ['linear'],
                    ['zoom'],
                    15.5,
                    0,
                    16,
                    1,
                ],
            },
            'source-layer': 'building',
        },
        {
            minzoom: 14,
            layout: { 'line-join': 'round', 'line-cap': 'round' },
            metadata: { 'mapbox:group': '49e1fe31d1c813174a5ab59acec3ade6' },
            filter: [
                'all',
                ['==', '$type', 'LineString'],
                [
                    'all',
                    ['!=', 'type', 'platform'],
                    ['in', 'class', 'path', 'pedestrian'],
                ],
            ],
            type: 'line',
            source: 'composite',
            id: 'pedestrian-path',
            paint: {
                'line-width': [
                    'interpolate',
                    ['exponential', 1.5],
                    ['zoom'],
                    14,
                    [
                        'match',
                        ['get', 'class'],
                        'pedestrian',
                        1,
                        'path',
                        0.75,
                        0.75,
                    ],
                    20,
                    ['match', ['get', 'class'], 'pedestrian', 8, 'path', 5, 5],
                ],
                'line-color': [
                    'match',
                    ['get', 'type'],
                    'sidewalk',
                    'hsl(38, 35%, 80%)',
                    'crossing',
                    'hsl(38, 35%, 80%)',
                    'hsl(38, 28%, 70%)',
                ],
            },
            'source-layer': 'road',
        },
        {
            layout: { 'line-join': 'round' },
            metadata: { 'mapbox:group': '49e1fe31d1c813174a5ab59acec3ade6' },
            filter: [
                'all',
                ['==', '$type', 'LineString'],
                [
                    'all',
                    ['!=', 'type', 'service:parking_aisle'],
                    ['==', 'structure', 'tunnel'],
                    [
                        'in',
                        'class',
                        'link',
                        'motorway',
                        'motorway_link',
                        'primary',
                        'secondary',
                        'service',
                        'street',
                        'street_limited',
                        'tertiary',
                        'track',
                        'trunk',
                    ],
                ],
            ],
            type: 'line',
            source: 'composite',
            id: 'tunnel',
            paint: {
                'line-width': [
                    'interpolate',
                    ['exponential', 1.5],
                    ['zoom'],
                    5,
                    [
                        'match',
                        ['get', 'class'],
                        'motorway',
                        0.5,
                        'trunk',
                        0.5,
                        'primary',
                        0.5,
                        'secondary',
                        0.01,
                        'tertiary',
                        0.01,
                        'street',
                        0,
                        'street_limited',
                        0,
                        'motorway_link',
                        0,
                        'service',
                        0,
                        'track',
                        0,
                        'link',
                        0,
                        0,
                    ],
                    12,
                    [
                        'match',
                        ['get', 'class'],
                        'motorway',
                        3,
                        'trunk',
                        3,
                        'primary',
                        3,
                        'secondary',
                        2,
                        'tertiary',
                        2,
                        'street',
                        0.5,
                        'street_limited',
                        0.5,
                        'motorway_link',
                        0.5,
                        'service',
                        0,
                        'track',
                        0,
                        'link',
                        0,
                        0,
                    ],
                    18,
                    [
                        'match',
                        ['get', 'class'],
                        'motorway',
                        30,
                        'trunk',
                        30,
                        'primary',
                        30,
                        'secondary',
                        24,
                        'tertiary',
                        24,
                        'street',
                        12,
                        'street_limited',
                        12,
                        'motorway_link',
                        12,
                        'service',
                        10,
                        'track',
                        10,
                        'link',
                        10,
                        10,
                    ],
                ],
                'line-color': [
                    'match',
                    ['get', 'class'],
                    'street',
                    'hsl(38, 100%, 98%)',
                    'street_limited',
                    'hsl(38, 100%, 98%)',
                    'service',
                    'hsl(38, 100%, 98%)',
                    'track',
                    'hsl(38, 100%, 98%)',
                    'link',
                    'hsl(38, 100%, 98%)',
                    'hsl(0, 0%, 100%)',
                ],
                'line-dasharray': [0.2, 0.2],
            },
            'source-layer': 'road',
        },
        {
            layout: { 'line-join': 'round', 'line-cap': 'round' },
            metadata: { 'mapbox:group': '49e1fe31d1c813174a5ab59acec3ade6' },
            filter: [
                'all',
                ['==', '$type', 'LineString'],
                [
                    'all',
                    ['!=', 'type', 'service:parking_aisle'],
                    ['!in', 'structure', 'bridge', 'tunnel'],
                    [
                        'in',
                        'class',
                        'link',
                        'motorway',
                        'motorway_link',
                        'primary',
                        'secondary',
                        'service',
                        'street',
                        'street_limited',
                        'tertiary',
                        'track',
                        'trunk',
                    ],
                ],
            ],
            type: 'line',
            source: 'composite',
            id: 'road',
            paint: {
                'line-width': [
                    'interpolate',
                    ['exponential', 1.5],
                    ['zoom'],
                    5,
                    [
                        'match',
                        ['get', 'class'],
                        'motorway',
                        0.5,
                        'trunk',
                        0.5,
                        'primary',
                        0.5,
                        'secondary',
                        0.01,
                        'tertiary',
                        0.01,
                        'street',
                        0,
                        'street_limited',
                        0,
                        'motorway_link',
                        0,
                        'service',
                        0,
                        'track',
                        0,
                        'link',
                        0,
                        0,
                    ],
                    12,
                    [
                        'match',
                        ['get', 'class'],
                        'motorway',
                        3,
                        'trunk',
                        3,
                        'primary',
                        3,
                        'secondary',
                        2,
                        'tertiary',
                        2,
                        'street',
                        0.5,
                        'street_limited',
                        0.5,
                        'motorway_link',
                        0.5,
                        'service',
                        0,
                        'track',
                        0,
                        'link',
                        0,
                        0,
                    ],
                    18,
                    [
                        'match',
                        ['get', 'class'],
                        'motorway',
                        30,
                        'trunk',
                        30,
                        'primary',
                        30,
                        'secondary',
                        24,
                        'tertiary',
                        24,
                        'street',
                        12,
                        'street_limited',
                        12,
                        'motorway_link',
                        12,
                        'service',
                        10,
                        'track',
                        10,
                        'link',
                        10,
                        10,
                    ],
                ],
                'line-color': [
                    'match',
                    ['get', 'class'],
                    'street',
                    'hsl(38, 100%, 98%)',
                    'street_limited',
                    'hsl(38, 100%, 98%)',
                    'service',
                    'hsl(38, 100%, 98%)',
                    'track',
                    'hsl(38, 100%, 98%)',
                    'link',
                    'hsl(38, 100%, 98%)',
                    'hsl(0, 0%, 100%)',
                ],
            },
            'source-layer': 'road',
        },
        {
            layout: { 'line-join': 'round' },
            metadata: { 'mapbox:group': '49e1fe31d1c813174a5ab59acec3ade6' },
            filter: [
                'all',
                ['==', '$type', 'LineString'],
                [
                    'all',
                    ['!=', 'type', 'service:parking_aisle'],
                    ['==', 'structure', 'bridge'],
                    [
                        'in',
                        'class',
                        'link',
                        'motorway',
                        'motorway_link',
                        'primary',
                        'secondary',
                        'service',
                        'street',
                        'street_limited',
                        'tertiary',
                        'track',
                        'trunk',
                    ],
                ],
            ],
            type: 'line',
            source: 'composite',
            id: 'bridge-case',
            paint: {
                'line-width': [
                    'interpolate',
                    ['exponential', 1.5],
                    ['zoom'],
                    10,
                    1,
                    16,
                    2,
                ],
                'line-color': 'hsl(38, 48%, 86%)',
                'line-gap-width': [
                    'interpolate',
                    ['exponential', 1.5],
                    ['zoom'],
                    5,
                    [
                        'match',
                        ['get', 'class'],
                        'motorway',
                        0.5,
                        'trunk',
                        0.5,
                        'primary',
                        0.5,
                        'secondary',
                        0.01,
                        'tertiary',
                        0.01,
                        'street',
                        0,
                        'street_limited',
                        0,
                        'motorway_link',
                        0,
                        'service',
                        0,
                        'track',
                        0,
                        'link',
                        0,
                        0,
                    ],
                    12,
                    [
                        'match',
                        ['get', 'class'],
                        'motorway',
                        3,
                        'trunk',
                        3,
                        'primary',
                        3,
                        'secondary',
                        2,
                        'tertiary',
                        2,
                        'street',
                        0.5,
                        'street_limited',
                        0.5,
                        'motorway_link',
                        0.5,
                        'service',
                        0,
                        'track',
                        0,
                        'link',
                        0,
                        0,
                    ],
                    18,
                    [
                        'match',
                        ['get', 'class'],
                        'motorway',
                        30,
                        'trunk',
                        30,
                        'primary',
                        30,
                        'secondary',
                        24,
                        'tertiary',
                        24,
                        'street',
                        12,
                        'street_limited',
                        12,
                        'motorway_link',
                        12,
                        'service',
                        10,
                        'track',
                        10,
                        'link',
                        10,
                        10,
                    ],
                ],
            },
            'source-layer': 'road',
        },
        {
            layout: { 'line-join': 'round', 'line-cap': 'round' },
            metadata: { 'mapbox:group': '49e1fe31d1c813174a5ab59acec3ade6' },
            filter: [
                'all',
                ['==', '$type', 'LineString'],
                [
                    'all',
                    ['!=', 'type', 'service:parking_aisle'],
                    ['==', 'structure', 'bridge'],
                    [
                        'in',
                        'class',
                        'link',
                        'motorway',
                        'motorway_link',
                        'primary',
                        'secondary',
                        'service',
                        'street',
                        'street_limited',
                        'tertiary',
                        'track',
                        'trunk',
                    ],
                ],
            ],
            type: 'line',
            source: 'composite',
            id: 'bridge',
            paint: {
                'line-width': [
                    'interpolate',
                    ['exponential', 1.5],
                    ['zoom'],
                    5,
                    [
                        'match',
                        ['get', 'class'],
                        'motorway',
                        0.5,
                        'trunk',
                        0.5,
                        'primary',
                        0.5,
                        'secondary',
                        0.01,
                        'tertiary',
                        0.01,
                        'street',
                        0,
                        'street_limited',
                        0,
                        'motorway_link',
                        0,
                        'service',
                        0,
                        'track',
                        0,
                        'link',
                        0,
                        0,
                    ],
                    12,
                    [
                        'match',
                        ['get', 'class'],
                        'motorway',
                        3,
                        'trunk',
                        3,
                        'primary',
                        3,
                        'secondary',
                        2,
                        'tertiary',
                        2,
                        'street',
                        0.5,
                        'street_limited',
                        0.5,
                        'motorway_link',
                        0.5,
                        'service',
                        0,
                        'track',
                        0,
                        'link',
                        0,
                        0,
                    ],
                    18,
                    [
                        'match',
                        ['get', 'class'],
                        'motorway',
                        30,
                        'trunk',
                        30,
                        'primary',
                        30,
                        'secondary',
                        24,
                        'tertiary',
                        24,
                        'street',
                        12,
                        'street_limited',
                        12,
                        'motorway_link',
                        12,
                        'service',
                        10,
                        'track',
                        10,
                        'link',
                        10,
                        10,
                    ],
                ],
                'line-color': [
                    'match',
                    ['get', 'class'],
                    'street',
                    'hsl(38, 100%, 98%)',
                    'street_limited',
                    'hsl(38, 100%, 98%)',
                    'service',
                    'hsl(38, 100%, 98%)',
                    'track',
                    'hsl(38, 100%, 98%)',
                    'link',
                    'hsl(38, 100%, 98%)',
                    'hsl(0, 0%, 100%)',
                ],
            },
            'source-layer': 'road',
        },
        {
            minzoom: 2,
            layout: { 'line-join': 'round', 'line-cap': 'round' },
            metadata: { 'mapbox:group': '49e1fe31d1c813174a5ab59acec3ade6' },
            filter: ['all', ['==', 'maritime', 0], ['>=', 'admin_level', 3]],
            type: 'line',
            source: 'composite',
            id: 'admin-state-province',
            paint: {
                'line-dasharray': [
                    'step',
                    ['zoom'],
                    ['literal', [2, 0]],
                    7,
                    ['literal', [2, 2, 6, 2]],
                ],
                'line-width': [
                    'interpolate',
                    ['linear'],
                    ['zoom'],
                    7,
                    0.75,
                    12,
                    1.5,
                ],
                'line-opacity': [
                    'interpolate',
                    ['linear'],
                    ['zoom'],
                    2,
                    0,
                    3,
                    1,
                ],
                'line-color': [
                    'step',
                    ['zoom'],
                    'hsl(0, 0%, 80%)',
                    4,
                    'hsl(0, 0%, 65%)',
                ],
            },
            'source-layer': 'admin',
        },
        {
            minzoom: 1,
            layout: { 'line-join': 'round', 'line-cap': 'round' },
            metadata: { 'mapbox:group': '49e1fe31d1c813174a5ab59acec3ade6' },
            filter: [
                'all',
                ['<=', 'admin_level', 2],
                ['==', 'disputed', 0],
                ['==', 'maritime', 0],
            ],
            type: 'line',
            source: 'composite',
            id: 'admin-country',
            paint: {
                'line-color': 'hsl(0, 0%, 50%)',
                'line-width': [
                    'interpolate',
                    ['linear'],
                    ['zoom'],
                    3,
                    0.5,
                    10,
                    2,
                ],
            },
            'source-layer': 'admin',
        },
        {
            minzoom: 1,
            layout: { 'line-join': 'round' },
            metadata: { 'mapbox:group': '49e1fe31d1c813174a5ab59acec3ade6' },
            filter: [
                'all',
                ['<=', 'admin_level', 2],
                ['==', 'disputed', 1],
                ['==', 'maritime', 0],
            ],
            type: 'line',
            source: 'composite',
            id: 'admin-country-disputed',
            paint: {
                'line-color': 'hsl(0, 0%, 50%)',
                'line-width': [
                    'interpolate',
                    ['linear'],
                    ['zoom'],
                    3,
                    0.5,
                    10,
                    2,
                ],
                'line-dasharray': [1.5, 1.5],
            },
            'source-layer': 'admin',
        },
        {
            minzoom: 12,
            layout: {
                'text-size': [
                    'interpolate',
                    ['linear'],
                    ['zoom'],
                    9,
                    [
                        'match',
                        ['get', 'class'],
                        'motorway',
                        10,
                        'trunk',
                        10,
                        'primary',
                        10,
                        'secondary',
                        10,
                        'tertiary',
                        10,
                        9,
                    ],
                    20,
                    [
                        'match',
                        ['get', 'class'],
                        'motorway',
                        15,
                        'trunk',
                        15,
                        'primary',
                        15,
                        'secondary',
                        15,
                        'tertiary',
                        15,
                        14,
                    ],
                ],
                'text-max-angle': 30,
                'text-font': ['Roboto Regular', 'Arial Unicode MS Regular'],
                'symbol-placement': 'line',
                'text-padding': 1,
                'text-rotation-alignment': 'map',
                'text-pitch-alignment': 'viewport',
                'text-field': ['get', 'name_en'],
            },
            metadata: { 'mapbox:group': '49e1fe31d1c813174a5ab59acec3ade6' },
            filter: [
                'in',
                'class',
                'link',
                'motorway',
                'pedestrian',
                'primary',
                'secondary',
                'street',
                'street_limited',
                'tertiary',
                'trunk',
            ],
            type: 'symbol',
            source: 'composite',
            id: 'road-label',
            paint: {
                'text-color': 'hsl(0, 0%, 0%)',
                'text-halo-color': 'hsl(0, 0%, 100%)',
                'text-halo-width': 1,
            },
            'source-layer': 'road_label',
        },
        {
            layout: {
                'text-line-height': 1.1,
                'text-size': [
                    'interpolate',
                    ['linear'],
                    ['zoom'],
                    10,
                    11,
                    18,
                    13,
                ],
                'icon-image': ['concat', ['get', 'maki'], '-11'],
                'text-max-angle': 38,
                'text-font': ['Roboto Regular', 'Arial Unicode MS Regular'],
                'text-padding': 2,
                'text-offset': [0, 0.75],
                'text-anchor': 'top',
                'text-field': ['get', 'name_en'],
                'text-max-width': 8,
            },
            metadata: { 'mapbox:group': '49e1fe31d1c813174a5ab59acec3ade6' },
            filter: ['<=', 'scalerank', 3],
            type: 'symbol',
            source: 'composite',
            id: 'poi-label',
            paint: {
                'text-color': 'hsl(38, 19%, 29%)',
                'text-halo-color': 'hsla(0, 0%, 100%, 0.75)',
                'text-halo-width': 1,
                'text-halo-blur': 0.5,
            },
            'source-layer': 'poi_label',
        },
        {
            layout: {
                'text-line-height': 1.1,
                'text-size': [
                    'interpolate',
                    ['linear'],
                    ['zoom'],
                    10,
                    12,
                    18,
                    18,
                ],
                'icon-image': [
                    'step',
                    ['zoom'],
                    ['concat', ['get', 'maki'], '-11'],
                    13,
                    ['concat', ['get', 'maki'], '-15'],
                ],
                'text-font': ['Roboto Regular', 'Arial Unicode MS Regular'],
                'text-padding': 2,
                'text-offset': [0, 0.75],
                'text-anchor': 'top',
                'text-field': [
                    'step',
                    ['zoom'],
                    ['get', 'ref'],
                    14,
                    ['get', 'name_en'],
                ],
                'text-max-width': 9,
            },
            metadata: { 'mapbox:group': '49e1fe31d1c813174a5ab59acec3ade6' },
            filter: ['<=', 'scalerank', 2],
            type: 'symbol',
            source: 'composite',
            id: 'airport-label',
            paint: {
                'text-color': 'hsl(38, 19%, 29%)',
                'text-halo-color': 'hsl(0, 0%, 100%)',
                'text-halo-width': 1,
            },
            'source-layer': 'airport_label',
        },
        {
            minzoom: 12,
            layout: {
                'text-field': ['get', 'name_en'],
                'text-transform': 'uppercase',
                'text-letter-spacing': 0.15,
                'text-max-width': 8,
                'text-font': ['Roboto Regular', 'Arial Unicode MS Regular'],
                'text-padding': 3,
                'text-size': [
                    'interpolate',
                    ['linear'],
                    ['zoom'],
                    12,
                    11,
                    16,
                    16,
                ],
            },
            metadata: { 'mapbox:group': '49e1fe31d1c813174a5ab59acec3ade6' },
            maxzoom: 15,
            filter: ['in', 'type', 'neighbourhood', 'suburb'],
            type: 'symbol',
            source: 'composite',
            id: 'place-neighborhood-suburb-label',
            paint: {
                'text-halo-color': 'hsl(0, 0%, 100%)',
                'text-halo-width': 1,
                'text-color': 'hsl(38, 62%, 21%)',
            },
            'source-layer': 'place_label',
        },
        {
            minzoom: 6,
            layout: {
                'text-size': [
                    'interpolate',
                    ['linear'],
                    ['zoom'],
                    5,
                    ['match', ['get', 'type'], 'town', 9.5, 8],
                    16,
                    ['match', ['get', 'type'], 'town', 20, 16],
                ],
                'text-font': [
                    'step',
                    ['zoom'],
                    ['literal', ['Roboto Regular', 'Arial Unicode MS Regular']],
                    12,
                    [
                        'match',
                        ['get', 'type'],
                        'town',
                        [
                            'literal',
                            ['Roboto Medium', 'Arial Unicode MS Regular'],
                        ],
                        [
                            'literal',
                            ['Roboto Regular', 'Arial Unicode MS Regular'],
                        ],
                    ],
                ],
                'text-max-width': 7,
                'text-field': ['get', 'name_en'],
            },
            metadata: { 'mapbox:group': '49e1fe31d1c813174a5ab59acec3ade6' },
            maxzoom: 14,
            filter: ['in', 'type', 'hamlet', 'town', 'village'],
            type: 'symbol',
            source: 'composite',
            id: 'place-town-village-hamlet-label',
            paint: {
                'text-color': 'hsl(0, 0%, 0%)',
                'text-halo-blur': 0.5,
                'text-halo-color': 'hsl(0, 0%, 100%)',
                'text-halo-width': 1,
            },
            'source-layer': 'place_label',
        },
        {
            minzoom: 1,
            layout: {
                'text-size': [
                    'interpolate',
                    ['linear'],
                    ['zoom'],
                    5,
                    12,
                    16,
                    22,
                ],
                'text-font': [
                    'literal',
                    ['Roboto Medium', 'Arial Unicode MS Regular'],
                ],
                'text-max-width': 10,
                'text-field': ['get', 'name_en'],
            },
            metadata: { 'mapbox:group': '49e1fe31d1c813174a5ab59acec3ade6' },
            maxzoom: 14,
            filter: ['all', ['!has', 'scalerank'], ['==', 'type', 'city']],
            type: 'symbol',
            source: 'composite',
            id: 'place-city-label-minor',
            paint: {
                'text-color': [
                    'interpolate',
                    ['linear'],
                    ['zoom'],
                    5,
                    'hsl(0, 0%, 33%)',
                    6,
                    'hsl(0, 0%, 0%)',
                ],
                'text-halo-blur': 0.5,
                'text-halo-color': 'hsl(0, 0%, 100%)',
                'text-halo-width': 1.25,
            },
            'source-layer': 'place_label',
        },
        {
            minzoom: 1,
            layout: {
                'text-size': [
                    'interpolate',
                    ['linear'],
                    ['zoom'],
                    5,
                    ['step', ['get', 'scalerank'], 14, 4, 12],
                    16,
                    ['step', ['get', 'scalerank'], 30, 4, 22],
                ],
                'text-font': [
                    'step',
                    ['zoom'],
                    ['literal', ['Roboto Medium', 'Arial Unicode MS Regular']],
                    10,
                    [
                        'step',
                        ['get', 'scalerank'],
                        ['literal', ['Roboto Bold', 'Arial Unicode MS Bold']],
                        5,
                        [
                            'literal',
                            ['Roboto Medium', 'Arial Unicode MS Regular'],
                        ],
                    ],
                ],
                'text-max-width': 10,
                'text-field': ['get', 'name_en'],
            },
            metadata: { 'mapbox:group': '49e1fe31d1c813174a5ab59acec3ade6' },
            maxzoom: 14,
            filter: ['all', ['==', 'type', 'city'], ['has', 'scalerank']],
            type: 'symbol',
            source: 'composite',
            id: 'place-city-label-major',
            paint: {
                'text-color': [
                    'interpolate',
                    ['linear'],
                    ['zoom'],
                    5,
                    'hsl(0, 0%, 33%)',
                    6,
                    'hsl(0, 0%, 0%)',
                ],
                'text-halo-blur': 0.5,
                'text-halo-color': 'hsl(0, 0%, 100%)',
                'text-halo-width': 1.25,
            },
            'source-layer': 'place_label',
        },
        {
            minzoom: 4,
            layout: {
                'text-line-height': 1.2,
                'text-size': [
                    'interpolate',
                    ['linear'],
                    ['zoom'],
                    4,
                    ['step', ['get', 'area'], 8, 20000, 9, 80000, 10],
                    9,
                    ['step', ['get', 'area'], 14, 20000, 18, 80000, 23],
                ],
                'text-transform': 'uppercase',
                'text-font': ['Roboto Black', 'Arial Unicode MS Bold'],
                'text-padding': 1,
                'text-field': [
                    'step',
                    ['zoom'],
                    [
                        'step',
                        ['get', 'area'],
                        ['get', 'abbr'],
                        80000,
                        ['get', 'name_en'],
                    ],
                    5,
                    ['get', 'name_en'],
                ],
                'text-letter-spacing': 0.2,
                'text-max-width': 6,
            },
            metadata: { 'mapbox:group': '49e1fe31d1c813174a5ab59acec3ade6' },
            maxzoom: 8,
            type: 'symbol',
            source: 'composite',
            id: 'state-label',
            paint: {
                'text-color': 'hsl(38, 7%, 64%)',
                'text-halo-width': 1,
                'text-halo-color': 'hsl(0, 0%, 100%)',
            },
            'source-layer': 'state_label',
        },
        {
            minzoom: 1,
            layout: {
                'text-field': ['get', 'name_en'],
                'text-max-width': [
                    'interpolate',
                    ['linear'],
                    ['zoom'],
                    0,
                    5,
                    3,
                    6,
                ],
                'text-font': [
                    'step',
                    ['zoom'],
                    ['literal', ['Roboto Medium', 'Arial Unicode MS Regular']],
                    4,
                    ['literal', ['Roboto Bold', 'Arial Unicode MS Bold']],
                ],
                'text-size': [
                    'interpolate',
                    ['linear'],
                    ['zoom'],
                    2,
                    ['step', ['get', 'scalerank'], 13, 3, 11, 5, 9],
                    9,
                    ['step', ['get', 'scalerank'], 35, 3, 27, 5, 22],
                ],
            },
            metadata: { 'mapbox:group': '49e1fe31d1c813174a5ab59acec3ade6' },
            maxzoom: 8,
            type: 'symbol',
            source: 'composite',
            id: 'country-label',
            paint: {
                'text-halo-width': 1.5,
                'text-halo-color': 'hsl(0, 0%, 100%)',
                'text-color': 'hsl(0, 0%, 0%)',
            },
            'source-layer': 'country_label',
        },
        {
            layout: { visibility: 'visible' },
            type: 'fill',
            source: 'composite',
            id: '00535-biogeoreg-v7',
            paint: {
                'fill-color': 'hsla(0, 0%, 0%, 0)',
                'fill-outline-color': [
                    'interpolate',
                    ['linear'],
                    ['zoom'],
                    0,
                    'hsl(0, 0%, 100%)',
                    22,
                    '#ffffff',
                ],
            },
            'source-layer': '00535_biogeoreg_v7_MapShaped_-9dxcxm',
        },
        {
            layout: { visibility: 'visible' },
            type: 'fill',
            source: 'composite',
            id: 'MCZ_existing2018',
            paint: { 'fill-color': '#02b6e3' },
            'source-layer': '00535_MCZ_EXISTING_2018_v2_Ma-1ar87o',
        },
        {
            layout: { visibility: 'visible' },
            type: 'fill',
            source: 'composite',
            id: 'MCZ_recommendedWales',
            paint: {
                'fill-color': [
                    'interpolate',
                    ['linear'],
                    ['zoom'],
                    0,
                    'hsl(58, 100%, 48%)',
                    22,
                    '#f4ed00',
                ],
            },
            'source-layer': '00535_MCZ_recommended_Wales_2-0w0loa',
        },
        {
            layout: { visibility: 'visible' },
            type: 'fill',
            source: 'composite',
            id: '00535-mcz-proposed-2018-v5-ma-7vquwh',
            paint: {
                'fill-color': [
                    'interpolate',
                    ['linear'],
                    ['zoom'],
                    0,
                    'hsl(336, 98%, 45%)',
                    22,
                    'hsl(336, 98%, 45%)',
                ],
            },
            'source-layer': '00535_MCZ_PROPOSED_2018_v5_ma-7vquwh',
        },
    ],
    created: '2018-06-26T09:05:31.308Z',
    modified: '2018-06-27T16:25:52.234Z',
    id: 'cjivgu4ye6het2rnvz5lt591p',
    owner: 'wildlifetrusts',
    visibility: 'private',
    protected: false,
    draft: false,
};
